  apiVersion: v1
  kind: Service
  metadata:
    name: frontend-service
  spec:
    type: LoadBalancer  # CrÃ©e un Load Balancer AWS pour exposer le frontend sur Internet
    selector:
      app: frontend     # Cible les pods avec le label `app: frontend`
    ports:
      - protocol: TCP
        port: 80         # Port exposÃ© par le Load Balancer (HTTP)
        targetPort: 5000 # Port des pods (ton application Flask Ã©coute sur 5000)
  ---
  #ici, Ã  la demande de EKS (kubernetes) AWS crÃ©e un Load Balancer qui Ã©coute sur le port 80 et redirige vers le port 5000 de mes pods frontend
  #â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  #â”‚                                                                               
  #â”‚   ğŸŒ Utilisateur                                                               
  #â”‚      â”‚                                                                       
  #â”‚      â–¼ (RequÃªte HTTP sur port 80)                                             
  #â”‚   ğŸšª [Load Balancer AWS]  â† CrÃ©Ã© automatiquement par Kubernetes              
  #â”‚      â”‚                                                                       
  #â”‚      â–¼ (Redirection vers port 5000)                                          
  #â”‚   ğŸ­ [Pods Frontend]  â† 2 rÃ©plicas (conteneurs Flask)                         
  #â”‚                                                                               
  #â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
